/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainview.java
 *
 * Created on 1-Dec-2009, 1:43:39 PM
 */

package client;

/**
 *
 * @author Pyro Penguin
 */

import java.io.*;
import java.net.*;
import javax.swing.*;
import common.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

public class mainview extends javax.swing.JFrame {

    public String target = "127.0.0.1";
    public int port = 1292;
    public String username;

    public boolean legit;




    private static Socket mConnection = null;
    public ServerConnection mainConnect = null;



    // UI STUFF

    protected static JTextArea consoleArea;
    protected static JTextArea lobbyArea;
    private final static String newline = "\n";


    /** Creates new form mainview */
    public mainview() {
        initComponents();
        
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entry = new javax.swing.JTextField();
        chatView = new javax.swing.JTabbedPane();
        sendBtn = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        scrollPane2 = new java.awt.ScrollPane();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        loginPassword = new javax.swing.JPasswordField();
        loginName = new javax.swing.JTextField();
        loginPort = new javax.swing.JTextField();
        loginIP = new javax.swing.JTextField();
        authButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entry.setName("entry"); // NOI18N
        entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryActionPerformed(evt);
            }
        });

        chatView.setName("chatView"); // NOI18N

        sendBtn.setText("send");
        sendBtn.setName("sendBtn"); // NOI18N
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        scrollPane1.setName("scrollPane1"); // NOI18N

        label1.setName("onlinelabel"); // NOI18N
        label1.setText("Online Users");

        jLabel1.setText("Friends");
        jLabel1.setName("jLabel1"); // NOI18N

        scrollPane2.setName("scrollPane2"); // NOI18N

        label2.setName("label2"); // NOI18N
        label2.setText("IP:");

        label3.setName("label3"); // NOI18N
        label3.setText("Port:");

        label4.setName("label4"); // NOI18N
        label4.setText("Nickname:");

        label5.setName("label5"); // NOI18N
        label5.setText("Password:");

        loginPassword.setText("1234");
        loginPassword.setName("loginPass"); // NOI18N

        loginName.setText("derp");
        loginName.setName("loginName"); // NOI18N

        loginPort.setText("1292");
        loginPort.setName("loginPort"); // NOI18N

        loginIP.setText("127.0.0.1");
        loginIP.setName("loginIP"); // NOI18N

        authButton.setText("Authenticate");
        authButton.setName("authButton"); // NOI18N
        authButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("STATUS:");
        jLabel2.setName("jLabel2"); // NOI18N

        stateLabel.setForeground(new java.awt.Color(255, 0, 51));
        stateLabel.setText("Disconnected");
        stateLabel.setName("stateLabel"); // NOI18N

        jLabel3.setText("Simple layout test");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(entry)
                            .addComponent(chatView, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(authButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loginName)
                                .addComponent(loginIP)
                                .addComponent(loginPort)
                                .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateLabel))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(chatView, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendBtn)
                    .addComponent(entry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(stateLabel))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryActionPerformed

    private void authButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authButtonActionPerformed
         loginController login = new loginController();
            // get connection data from form
            target = loginIP.getText();
            port = Integer.parseInt(loginPort.getText());
            String pass = loginPassword.getText();
            username = loginName.getText();
                      

            System.out.println("login:" + target);
            System.out.println("port:" + port);
            System.out.println("pass:" + pass);
            System.out.println("name:" + username);

            /* Gets form data and creates a new connection with it */
            connect(pass);

    }//GEN-LAST:event_authButtonActionPerformed

    public void connect(String password) {
        try {

        InetAddress address = InetAddress.getByName(target);
        mConnection = new Socket(target, port);

        mainConnect = new ServerConnection(mConnection);
        Thread thread = new Thread((Runnable) mainConnect);
        thread.start();

        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        NetworkMessage lmsg = new NetworkMessage(NetworkMessage.NetworkAction.LOGIN,new String[] {username, password });
        mainConnect.sendNetworkMsg(lmsg);

        stateLabel.setText("Connected");
        stateLabel.setForeground(Color.green);
        consoleWrite("Connection to the Server Confirmed!");
        consoleWrite("Username: " + username);
        consoleWrite("Password: *****");
        consoleWrite("IP: " + target);
        consoleWrite("Port: " + port);
        consoleWrite("-> Joining Lobby...");
        joinLobby();
        }
        catch(Exception e) {
        System.out.print("Error");
    }
    }
    
    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        String txtmsg = entry.getText();
        entry.setText(null);
        NetworkMessage gmsg = new NetworkMessage(NetworkMessage.NetworkAction.IM,new String[] {username, txtmsg });
        mainConnect.sendNetworkMsg(gmsg);
        consoleWrite(txtmsg);
        
    }//GEN-LAST:event_sendBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainview().setVisible(true);
                build();

            }
        });
    }

    private static void build() {
        // marker for initial
                consoleArea = new JTextArea(5, 20);
                consoleArea.setEditable(false);
                Insets insets = new Insets(5,5,5,5);
                consoleArea.setMargin(insets);
                JScrollPane consolePane = new JScrollPane(consoleArea);
                JComponent console = makeTextPanel("Console");
                chatView.addTab("Console", consolePane);
                consolePane.setBackground(Color.white);
                //chatView.setTabComponentAt(0,
                // new ButtonTabComponent(chatView));

                consoleWrite("Program Initialized...");
                consoleWrite("----------------------");


    }

    private static void consoleWrite(String a) {
        String text = a;
        consoleArea.append(text + newline);

    }

    private static void joinLobby(){

                lobbyArea = new JTextArea(5, 20);
                lobbyArea.setEditable(false);
                Insets insets = new Insets(5,5,5,5);
                lobbyArea.setMargin(insets);
                JScrollPane lobbyPane = new JScrollPane(lobbyArea);
                JComponent lobby = makeTextPanel("Lobby");
                chatView.addTab("Lobby", lobbyPane);
                lobbyPane.setBackground(Color.white);
                chatView.setTabComponentAt(1,
                new ButtonTabComponent(chatView));

    }

    protected static JComponent makeTextPanel(String text) {
        JPanel name = new JPanel(false);
        name.setLayout(new GridLayout(1, 1));
        return name;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authButton;
    private static javax.swing.JTabbedPane chatView;
    private javax.swing.JTextField entry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JTextField loginIP;
    private javax.swing.JTextField loginName;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField loginPort;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private javax.swing.JButton sendBtn;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration//GEN-END:variables

}
