/*
 * QuickChatprojAboutBox.java
 */

package client;

import org.jdesktop.application.Action;

public class QuickChatprojAboutBox extends javax.swing.JDialog {

    public QuickChatprojAboutBox(/*java.awt.Frame parent*/) {
        //super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);


    }

    /*@Action
    public void closeAboutBox() {
        dispose();
    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        lb_member2 = new javax.swing.JLabel();
        lb_member3 = new javax.swing.JLabel();
        lb_member4 = new javax.swing.JLabel();
        lb_member5 = new javax.swing.JLabel();
        lb_member1 = new javax.swing.JLabel();
        lb_groupNo = new javax.swing.JLabel();
        appDescLabel = new javax.swing.JLabel();
        appTitleLabel = new javax.swing.JLabel();
        appVersionLabel = new javax.swing.JLabel();
        lb_group = new javax.swing.JLabel();
        lb_team = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(QuickChatprojAboutBox.class);
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        lb_member2.setText(resourceMap.getString("lb_member2.text")); // NOI18N
        lb_member2.setName("lb_member2"); // NOI18N

        lb_member3.setText(resourceMap.getString("lb_member3.text")); // NOI18N
        lb_member3.setName("lb_member3"); // NOI18N

        lb_member4.setText(resourceMap.getString("lb_member4.text")); // NOI18N
        lb_member4.setName("lb_member4"); // NOI18N

        lb_member5.setText(resourceMap.getString("lb_member5.text")); // NOI18N
        lb_member5.setName("lb_member5"); // NOI18N

        lb_member1.setText(resourceMap.getString("lb_member1.text")); // NOI18N
        lb_member1.setName("lb_member1"); // NOI18N

        lb_groupNo.setText(resourceMap.getString("lb_groupNo.text")); // NOI18N
        lb_groupNo.setName("lb_groupNo"); // NOI18N

        appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
        appDescLabel.setName("appDescLabel"); // NOI18N

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        appTitleLabel.setText(resourceMap.getString("appTitleLabel.text")); // NOI18N
        appTitleLabel.setName("appTitleLabel"); // NOI18N

        appVersionLabel.setText(resourceMap.getString("appVersionLabel.text")); // NOI18N
        appVersionLabel.setEnabled(false);
        appVersionLabel.setName("appVersionLabel"); // NOI18N

        lb_group.setFont(lb_group.getFont().deriveFont(lb_group.getFont().getStyle() | java.awt.Font.BOLD));
        lb_group.setText(resourceMap.getString("lb_group.text")); // NOI18N
        lb_group.setName("lb_group"); // NOI18N

        lb_team.setFont(lb_team.getFont().deriveFont(lb_team.getFont().getStyle() | java.awt.Font.BOLD));
        lb_team.setText(resourceMap.getString("lb_team.text")); // NOI18N
        lb_team.setName("lb_team"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(appTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appVersionLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_group)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_groupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_team)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_member1)
                            .addComponent(lb_member5)
                            .addComponent(lb_member2)
                            .addComponent(lb_member3)
                            .addComponent(lb_member4)))
                    .addComponent(appDescLabel))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appTitleLabel)
                    .addComponent(appVersionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(appDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_groupNo)
                    .addComponent(lb_group))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_team)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_member1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_member2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_member3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_member4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_member5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appDescLabel;
    private javax.swing.JLabel appTitleLabel;
    private javax.swing.JLabel appVersionLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel lb_group;
    private javax.swing.JLabel lb_groupNo;
    private javax.swing.JLabel lb_member1;
    private javax.swing.JLabel lb_member2;
    private javax.swing.JLabel lb_member3;
    private javax.swing.JLabel lb_member4;
    private javax.swing.JLabel lb_member5;
    private javax.swing.JLabel lb_team;
    // End of variables declaration//GEN-END:variables
    
}
